name: CI

on:
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Run tests
    runs-on: ubuntu-latest
    steps:

      #
      #     Setting up environment
      #
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build & Test module
        run: |
          go get -v -t -d ./...
          go test -v  ./...
          go build -v .
        working-directory: './'